# Generated by Django 5.0.3 on 2024-04-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Tenis',
        ),
    ]
