# Generated by Django 5.0.3 on 2024-04-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_rename_product_tenis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenis',
            name='type',
            field=models.CharField(choices=[('Correr', 'Correr'), ('Casuales', 'Casuales'), ('Bota', 'Bota')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
