# Generated by Django 5.0.3 on 2024-04-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_tenis_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenis',
            name='name',
        ),
        migrations.AddField(
            model_name='tenis',
            name='Modelo',
            field=models.CharField(choices=[('Running precision VI', 'Running precision VI'), ('BrandNewElegant', 'BrandNewElegant'), ('Los del CR7', 'Los del CR7')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
