# Generated by Django 5.0.3 on 2024-04-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_remove_tenis_name_tenis_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenis',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='price',
        ),
        migrations.AddField(
            model_name='tenis',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
